name: null
favicon: null
layout_spectrum: 0.007254234282299876
typography_spectrum: 0.09570121392607689
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.43669469677843153
  lightness: 0.36684213136322796
  saturation: 0.4486427519004792
  rhythmicContrast: 0.8312383990269154
purpose: []
